services:
  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent
    environment:
      - DD_API_KEY=
      - DD_SITE=datadoghq.com
      - DD_ENV=local
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    volumes:
      - /var/run/datadog:/var/run/datadog
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/log:/host/var/log:ro
    networks:
      - datadog-network
    ports:
      - "8126:8126" # APM
      - "8125:8125/udp" # DogStatsD

  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=datadog-demo-app-be
      - DD_VERSION=1.0.1
      - DD_ENV=local
      - DD_TRACE_DEBUG=true
      - DD_TRACE_ENABLED=true
      - NODE_ENV=local
    depends_on:
      - datadog-agent
    networks:
      - datadog-network

  frontend:
    image: httpd:2.4
    container_name: frontend
    volumes:
      - ./frontend:/usr/local/apache2/htdocs
    ports:
      - "8080:80"
    networks:
      - datadog-network

networks:
  datadog-network:
    driver: bridge
