apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: datadog-demo-app
build:
  artifacts:
    - image: backend
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/backend.yaml
    - k8s/frontend.yaml
